/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ASSIGN</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see scheduling.dsl.DslPackage#getASSIGN()
 * @model
 * @generated
 */
public interface ASSIGN extends Action
{
} // ASSIGN
