/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Atomic#getVar <em>Var</em>}</li>
 *   <li>{@link scheduling.dsl.Atomic#getLele <em>Lele</em>}</li>
 *   <li>{@link scheduling.dsl.Atomic#getCharseq <em>Charseq</em>}</li>
 *   <li>{@link scheduling.dsl.Atomic#getString <em>String</em>}</li>
 *   <li>{@link scheduling.dsl.Atomic#getSysvar <em>Sysvar</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getAtomic()
 * @model
 * @generated
 */
public interface Atomic extends Expression
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(QualifiedNames)
   * @see scheduling.dsl.DslPackage#getAtomic_Var()
   * @model containment="true"
   * @generated
   */
  QualifiedNames getVar();

  /**
   * Sets the value of the '{@link scheduling.dsl.Atomic#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(QualifiedNames value);

  /**
   * Returns the value of the '<em><b>Lele</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lele</em>' containment reference.
   * @see #setLele(ListElement)
   * @see scheduling.dsl.DslPackage#getAtomic_Lele()
   * @model containment="true"
   * @generated
   */
  ListElement getLele();

  /**
   * Sets the value of the '{@link scheduling.dsl.Atomic#getLele <em>Lele</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lele</em>' containment reference.
   * @see #getLele()
   * @generated
   */
  void setLele(ListElement value);

  /**
   * Returns the value of the '<em><b>Charseq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Charseq</em>' attribute.
   * @see #setCharseq(String)
   * @see scheduling.dsl.DslPackage#getAtomic_Charseq()
   * @model
   * @generated
   */
  String getCharseq();

  /**
   * Sets the value of the '{@link scheduling.dsl.Atomic#getCharseq <em>Charseq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Charseq</em>' attribute.
   * @see #getCharseq()
   * @generated
   */
  void setCharseq(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see scheduling.dsl.DslPackage#getAtomic_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link scheduling.dsl.Atomic#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Sysvar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sysvar</em>' containment reference.
   * @see #setSysvar(SysVar)
   * @see scheduling.dsl.DslPackage#getAtomic_Sysvar()
   * @model containment="true"
   * @generated
   */
  SysVar getSysvar();

  /**
   * Sets the value of the '{@link scheduling.dsl.Atomic#getSysvar <em>Sysvar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sysvar</em>' containment reference.
   * @see #getSysvar()
   * @generated
   */
  void setSysvar(SysVar value);

} // Atomic
