/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.CheckPoint#getPointid <em>Pointid</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getCheckPoint()
 * @model
 * @generated
 */
public interface CheckPoint extends Statement
{
  /**
   * Returns the value of the '<em><b>Pointid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointid</em>' containment reference.
   * @see #setPointid(PointID)
   * @see scheduling.dsl.DslPackage#getCheckPoint_Pointid()
   * @model containment="true"
   * @generated
   */
  PointID getPointid();

  /**
   * Sets the value of the '{@link scheduling.dsl.CheckPoint#getPointid <em>Pointid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pointid</em>' containment reference.
   * @see #getPointid()
   * @generated
   */
  void setPointid(PointID value);

} // CheckPoint
