/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Component#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.Component#getTemplate <em>Template</em>}</li>
 *   <li>{@link scheduling.dsl.Component#getStm <em>Stm</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see scheduling.dsl.DslPackage#getComponent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link scheduling.dsl.Component#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Template</em>' containment reference.
   * @see #setTemplate(SetTemplate)
   * @see scheduling.dsl.DslPackage#getComponent_Template()
   * @model containment="true"
   * @generated
   */
  SetTemplate getTemplate();

  /**
   * Sets the value of the '{@link scheduling.dsl.Component#getTemplate <em>Template</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Template</em>' containment reference.
   * @see #getTemplate()
   * @generated
   */
  void setTemplate(SetTemplate value);

  /**
   * Returns the value of the '<em><b>Stm</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stm</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getComponent_Stm()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStm();

} // Component
