/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Configuration#getVar <em>Var</em>}</li>
 *   <li>{@link scheduling.dsl.Configuration#getCollection <em>Collection</em>}</li>
 *   <li>{@link scheduling.dsl.Configuration#getProc <em>Proc</em>}</li>
 *   <li>{@link scheduling.dsl.Configuration#getNul <em>Nul</em>}</li>
 *   <li>{@link scheduling.dsl.Configuration#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.VarInit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getConfiguration_Var()
   * @model containment="true"
   * @generated
   */
  EList<VarInit> getVar();

  /**
   * Returns the value of the '<em><b>Collection</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.CollectionInit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getConfiguration_Collection()
   * @model containment="true"
   * @generated
   */
  EList<CollectionInit> getCollection();

  /**
   * Returns the value of the '<em><b>Proc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc</em>' attribute.
   * @see #setProc(String)
   * @see scheduling.dsl.DslPackage#getConfiguration_Proc()
   * @model
   * @generated
   */
  String getProc();

  /**
   * Sets the value of the '{@link scheduling.dsl.Configuration#getProc <em>Proc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc</em>' attribute.
   * @see #getProc()
   * @generated
   */
  void setProc(String value);

  /**
   * Returns the value of the '<em><b>Nul</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nul</em>' attribute.
   * @see #setNul(String)
   * @see scheduling.dsl.DslPackage#getConfiguration_Nul()
   * @model
   * @generated
   */
  String getNul();

  /**
   * Sets the value of the '{@link scheduling.dsl.Configuration#getNul <em>Nul</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nul</em>' attribute.
   * @see #getNul()
   * @generated
   */
  void setNul(String value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Element)
   * @see scheduling.dsl.DslPackage#getConfiguration_Element()
   * @model containment="true"
   * @generated
   */
  Element getElement();

  /**
   * Sets the value of the '{@link scheduling.dsl.Configuration#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Element value);

} // Configuration
