/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Constraints#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getConstraints()
 * @model
 * @generated
 */
public interface Constraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getConstraints_Constraint()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getConstraint();

} // Constraints
