/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Define</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Define#getReflist <em>Reflist</em>}</li>
 *   <li>{@link scheduling.dsl.Define#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getDefine()
 * @model
 * @generated
 */
public interface Define extends EObject
{
  /**
   * Returns the value of the '<em><b>Reflist</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.RefList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reflist</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getDefine_Reflist()
   * @model containment="true"
   * @generated
   */
  EList<RefList> getReflist();

  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getDefine_Function()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunction();

} // Define
