/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Element#getProcess <em>Process</em>}</li>
 *   <li>{@link scheduling.dsl.Element#getParaAssign <em>Para Assign</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Process</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' containment reference.
   * @see #setProcess(scheduling.dsl.Process)
   * @see scheduling.dsl.DslPackage#getElement_Process()
   * @model containment="true"
   * @generated
   */
  scheduling.dsl.Process getProcess();

  /**
   * Sets the value of the '{@link scheduling.dsl.Element#getProcess <em>Process</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' containment reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(scheduling.dsl.Process value);

  /**
   * Returns the value of the '<em><b>Para Assign</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Para Assign</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getElement_ParaAssign()
   * @model containment="true"
   * @generated
   */
  EList<Value> getParaAssign();

} // Element
