/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Empty Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.EmptyExpression#getCol <em>Col</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getEmptyExpression()
 * @model
 * @generated
 */
public interface EmptyExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' containment reference.
   * @see #setCol(SchedulerSet)
   * @see scheduling.dsl.DslPackage#getEmptyExpression_Col()
   * @model containment="true"
   * @generated
   */
  SchedulerSet getCol();

  /**
   * Sets the value of the '{@link scheduling.dsl.EmptyExpression#getCol <em>Col</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' containment reference.
   * @see #getCol()
   * @generated
   */
  void setCol(SchedulerSet value);

} // EmptyExpression
