/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.EnumDec#getType <em>Type</em>}</li>
 *   <li>{@link scheduling.dsl.EnumDec#getEnumele <em>Enumele</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getEnumDec()
 * @model
 * @generated
 */
public interface EnumDec extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(EnumType)
   * @see scheduling.dsl.DslPackage#getEnumDec_Type()
   * @model containment="true"
   * @generated
   */
  EnumType getType();

  /**
   * Sets the value of the '{@link scheduling.dsl.EnumDec#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(EnumType value);

  /**
   * Returns the value of the '<em><b>Enumele</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumele</em>' attribute list.
   * @see scheduling.dsl.DslPackage#getEnumDec_Enumele()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnumele();

} // EnumDec
