/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Opt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.EventOpt#getOpt <em>Opt</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getEventOpt()
 * @model
 * @generated
 */
public interface EventOpt extends EObject
{
  /**
   * Returns the value of the '<em><b>Opt</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Opt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getEventOpt_Opt()
   * @model containment="true"
   * @generated
   */
  EList<Opt> getOpt();

} // EventOpt
