/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exist P</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ExistP#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getExistP()
 * @model
 * @generated
 */
public interface ExistP extends Expression
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see scheduling.dsl.DslPackage#getExistP_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link scheduling.dsl.ExistP#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

} // ExistP
