/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Para</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.FuncPara#getPara <em>Para</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getFuncPara()
 * @model
 * @generated
 */
public interface FuncPara extends EObject
{
  /**
   * Returns the value of the '<em><b>Para</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Para</em>' attribute list.
   * @see scheduling.dsl.DslPackage#getFuncPara_Para()
   * @model unique="false"
   * @generated
   */
  EList<String> getPara();

} // FuncPara
