/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Function#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.Function#getFuncpara <em>Funcpara</em>}</li>
 *   <li>{@link scheduling.dsl.Function#getSequence <em>Sequence</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see scheduling.dsl.DslPackage#getFunction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link scheduling.dsl.Function#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Funcpara</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Funcpara</em>' containment reference.
   * @see #setFuncpara(FuncPara)
   * @see scheduling.dsl.DslPackage#getFunction_Funcpara()
   * @model containment="true"
   * @generated
   */
  FuncPara getFuncpara();

  /**
   * Sets the value of the '{@link scheduling.dsl.Function#getFuncpara <em>Funcpara</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Funcpara</em>' containment reference.
   * @see #getFuncpara()
   * @generated
   */
  void setFuncpara(FuncPara value);

  /**
   * Returns the value of the '<em><b>Sequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence</em>' containment reference.
   * @see #setSequence(SequenceAction)
   * @see scheduling.dsl.DslPackage#getFunction_Sequence()
   * @model containment="true"
   * @generated
   */
  SequenceAction getSequence();

  /**
   * Sets the value of the '{@link scheduling.dsl.Function#getSequence <em>Sequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sequence</em>' containment reference.
   * @see #getSequence()
   * @generated
   */
  void setSequence(SequenceAction value);

} // Function
