/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Code Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.GenCodeStatement#getComp <em>Comp</em>}</li>
 *   <li>{@link scheduling.dsl.GenCodeStatement#getSt <em>St</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getGenCodeStatement()
 * @model
 * @generated
 */
public interface GenCodeStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' attribute.
   * @see #setComp(String)
   * @see scheduling.dsl.DslPackage#getGenCodeStatement_Comp()
   * @model
   * @generated
   */
  String getComp();

  /**
   * Sets the value of the '{@link scheduling.dsl.GenCodeStatement#getComp <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' attribute.
   * @see #getComp()
   * @generated
   */
  void setComp(String value);

  /**
   * Returns the value of the '<em><b>St</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>St</em>' containment reference.
   * @see #setSt(Expression)
   * @see scheduling.dsl.DslPackage#getGenCodeStatement_St()
   * @model containment="true"
   * @generated
   */
  Expression getSt();

  /**
   * Sets the value of the '{@link scheduling.dsl.GenCodeStatement#getSt <em>St</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>St</em>' containment reference.
   * @see #getSt()
   * @generated
   */
  void setSt(Expression value);

} // GenCodeStatement
