/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.GenPart#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link scheduling.dsl.GenPart#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.GenPart#getPosfix <em>Posfix</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getGenPart()
 * @model
 * @generated
 */
public interface GenPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see scheduling.dsl.DslPackage#getGenPart_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link scheduling.dsl.GenPart#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see scheduling.dsl.DslPackage#getGenPart_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link scheduling.dsl.GenPart#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Posfix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Posfix</em>' attribute.
   * @see #setPosfix(String)
   * @see scheduling.dsl.DslPackage#getGenPart_Posfix()
   * @model
   * @generated
   */
  String getPosfix();

  /**
   * Sets the value of the '{@link scheduling.dsl.GenPart#getPosfix <em>Posfix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Posfix</em>' attribute.
   * @see #getPosfix()
   * @generated
   */
  void setPosfix(String value);

} // GenPart
