/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.GetName#getProc <em>Proc</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getGetName()
 * @model
 * @generated
 */
public interface GetName extends Expression
{
  /**
   * Returns the value of the '<em><b>Proc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc</em>' containment reference.
   * @see #setProc(scheduling.dsl.Process)
   * @see scheduling.dsl.DslPackage#getGetName_Proc()
   * @model containment="true"
   * @generated
   */
  scheduling.dsl.Process getProc();

  /**
   * Sets the value of the '{@link scheduling.dsl.GetName#getProc <em>Proc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc</em>' containment reference.
   * @see #getProc()
   * @generated
   */
  void setProc(scheduling.dsl.Process value);

} // GetName
