/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.GetProcess#getColFrom <em>Col From</em>}</li>
 *   <li>{@link scheduling.dsl.GetProcess#getChange <em>Change</em>}</li>
 *   <li>{@link scheduling.dsl.GetProcess#getTime <em>Time</em>}</li>
 *   <li>{@link scheduling.dsl.GetProcess#getColTo <em>Col To</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getGetProcess()
 * @model
 * @generated
 */
public interface GetProcess extends Statement
{
  /**
   * Returns the value of the '<em><b>Col From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col From</em>' containment reference.
   * @see #setColFrom(SchedulerSet)
   * @see scheduling.dsl.DslPackage#getGetProcess_ColFrom()
   * @model containment="true"
   * @generated
   */
  SchedulerSet getColFrom();

  /**
   * Sets the value of the '{@link scheduling.dsl.GetProcess#getColFrom <em>Col From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col From</em>' containment reference.
   * @see #getColFrom()
   * @generated
   */
  void setColFrom(SchedulerSet value);

  /**
   * Returns the value of the '<em><b>Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Change</em>' containment reference.
   * @see #setChange(ChangeAction)
   * @see scheduling.dsl.DslPackage#getGetProcess_Change()
   * @model containment="true"
   * @generated
   */
  ChangeAction getChange();

  /**
   * Sets the value of the '{@link scheduling.dsl.GetProcess#getChange <em>Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Change</em>' containment reference.
   * @see #getChange()
   * @generated
   */
  void setChange(ChangeAction value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Expression)
   * @see scheduling.dsl.DslPackage#getGetProcess_Time()
   * @model containment="true"
   * @generated
   */
  Expression getTime();

  /**
   * Sets the value of the '{@link scheduling.dsl.GetProcess#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Expression value);

  /**
   * Returns the value of the '<em><b>Col To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col To</em>' containment reference.
   * @see #setColTo(SchedulerSet)
   * @see scheduling.dsl.DslPackage#getGetProcess_ColTo()
   * @model containment="true"
   * @generated
   */
  SchedulerSet getColTo();

  /**
   * Sets the value of the '{@link scheduling.dsl.GetProcess#getColTo <em>Col To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col To</em>' containment reference.
   * @see #getColTo()
   * @generated
   */
  void setColTo(SchedulerSet value);

} // GetProcess
