/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Handler Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.HandlerDef#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getHandlerDef()
 * @model
 * @generated
 */
public interface HandlerDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.EventDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getHandlerDef_Event()
   * @model containment="true"
   * @generated
   */
  EList<EventDef> getEvent();

} // HandlerDef
