/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Has Name Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.HasNameExpression#getProc <em>Proc</em>}</li>
 *   <li>{@link scheduling.dsl.HasNameExpression#getPN <em>PN</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getHasNameExpression()
 * @model
 * @generated
 */
public interface HasNameExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Proc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc</em>' containment reference.
   * @see #setProc(scheduling.dsl.Process)
   * @see scheduling.dsl.DslPackage#getHasNameExpression_Proc()
   * @model containment="true"
   * @generated
   */
  scheduling.dsl.Process getProc();

  /**
   * Sets the value of the '{@link scheduling.dsl.HasNameExpression#getProc <em>Proc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc</em>' containment reference.
   * @see #getProc()
   * @generated
   */
  void setProc(scheduling.dsl.Process value);

  /**
   * Returns the value of the '<em><b>PN</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PN</em>' attribute.
   * @see #setPN(String)
   * @see scheduling.dsl.DslPackage#getHasNameExpression_PN()
   * @model
   * @generated
   */
  String getPN();

  /**
   * Sets the value of the '{@link scheduling.dsl.HasNameExpression#getPN <em>PN</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PN</em>' attribute.
   * @see #getPN()
   * @generated
   */
  void setPN(String value);

} // HasNameExpression
