/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface Parameter List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.InterfaceParameterList#getPara <em>Para</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getInterfaceParameterList()
 * @model
 * @generated
 */
public interface InterfaceParameterList extends EObject
{
  /**
   * Returns the value of the '<em><b>Para</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.InterfaceParameterDeclare}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Para</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getInterfaceParameterList_Para()
   * @model containment="true"
   * @generated
   */
  EList<InterfaceParameterDeclare> getPara();

} // InterfaceParameterList
