/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invariants</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see scheduling.dsl.DslPackage#getInvariants()
 * @model
 * @generated
 */
public interface Invariants extends EObject
{
} // Invariants
