/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ND Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ND_Behavior#getCond <em>Cond</em>}</li>
 *   <li>{@link scheduling.dsl.ND_Behavior#getEventtemplate <em>Eventtemplate</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getND_Behavior()
 * @model
 * @generated
 */
public interface ND_Behavior extends EObject
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Expression)
   * @see scheduling.dsl.DslPackage#getND_Behavior_Cond()
   * @model containment="true"
   * @generated
   */
  Expression getCond();

  /**
   * Sets the value of the '{@link scheduling.dsl.ND_Behavior#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Expression value);

  /**
   * Returns the value of the '<em><b>Eventtemplate</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.EventTemplate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventtemplate</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getND_Behavior_Eventtemplate()
   * @model containment="true"
   * @generated
   */
  EList<EventTemplate> getEventtemplate();

} // ND_Behavior
