/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.NumValue#getMinus <em>Minus</em>}</li>
 *   <li>{@link scheduling.dsl.NumValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getNumValue()
 * @model
 * @generated
 */
public interface NumValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Minus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minus</em>' attribute.
   * @see #setMinus(String)
   * @see scheduling.dsl.DslPackage#getNumValue_Minus()
   * @model
   * @generated
   */
  String getMinus();

  /**
   * Sets the value of the '{@link scheduling.dsl.NumValue#getMinus <em>Minus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minus</em>' attribute.
   * @see #getMinus()
   * @generated
   */
  void setMinus(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see scheduling.dsl.DslPackage#getNumValue_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link scheduling.dsl.NumValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // NumValue
