/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Para List Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ParaListItem#getItem <em>Item</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getParaListItem()
 * @model
 * @generated
 */
public interface ParaListItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Item</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.RefListItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getParaListItem_Item()
   * @model containment="true"
   * @generated
   */
  EList<RefListItem> getItem();

} // ParaListItem
