/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Permutation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Permutation#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getPermutation()
 * @model
 * @generated
 */
public interface Permutation extends EObject
{
  /**
   * Returns the value of the '<em><b>Step</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' attribute.
   * @see #setStep(int)
   * @see scheduling.dsl.DslPackage#getPermutation_Step()
   * @model
   * @generated
   */
  int getStep();

  /**
   * Sets the value of the '{@link scheduling.dsl.Permutation#getStep <em>Step</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' attribute.
   * @see #getStep()
   * @generated
   */
  void setStep(int value);

} // Permutation
