/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Init</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ProcessInit#getOrder <em>Order</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getProcessInit()
 * @model
 * @generated
 */
public interface ProcessInit extends EObject
{
  /**
   * Returns the value of the '<em><b>Order</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.Set}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getProcessInit_Order()
   * @model containment="true"
   * @generated
   */
  EList<Set> getOrder();

} // ProcessInit
