/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ProcessConfig#getProcinit <em>Procinit</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getProcessConfig()
 * @model
 * @generated
 */
public interface ProcessConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Procinit</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.ConfigProcess}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procinit</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getProcessConfig_Procinit()
   * @model containment="true"
   * @generated
   */
  EList<ConfigProcess> getProcinit();

} // ProcessConfig
