/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ProcessDSL#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getParent <em>Parent</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getProcessdata <em>Processdata</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getConstraints <em>Constraints</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getProcess <em>Process</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getProcessconfig <em>Processconfig</em>}</li>
 *   <li>{@link scheduling.dsl.ProcessDSL#getProcessinit <em>Processinit</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getProcessDSL()
 * @model
 * @generated
 */
public interface ProcessDSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' attribute.
   * @see #setParent(String)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Parent()
   * @model
   * @generated
   */
  String getParent();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getParent <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' attribute.
   * @see #getParent()
   * @generated
   */
  void setParent(String value);

  /**
   * Returns the value of the '<em><b>Processdata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processdata</em>' containment reference.
   * @see #setProcessdata(ProcessDataDef)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Processdata()
   * @model containment="true"
   * @generated
   */
  ProcessDataDef getProcessdata();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getProcessdata <em>Processdata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Processdata</em>' containment reference.
   * @see #getProcessdata()
   * @generated
   */
  void setProcessdata(ProcessDataDef value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference.
   * @see #setConstraints(Constraints)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Constraints()
   * @model containment="true"
   * @generated
   */
  Constraints getConstraints();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getConstraints <em>Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraints</em>' containment reference.
   * @see #getConstraints()
   * @generated
   */
  void setConstraints(Constraints value);

  /**
   * Returns the value of the '<em><b>Process</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.ProcessDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getProcessDSL_Process()
   * @model containment="true"
   * @generated
   */
  EList<ProcessDef> getProcess();

  /**
   * Returns the value of the '<em><b>Processconfig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processconfig</em>' containment reference.
   * @see #setProcessconfig(ProcessConfig)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Processconfig()
   * @model containment="true"
   * @generated
   */
  ProcessConfig getProcessconfig();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getProcessconfig <em>Processconfig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Processconfig</em>' containment reference.
   * @see #getProcessconfig()
   * @generated
   */
  void setProcessconfig(ProcessConfig value);

  /**
   * Returns the value of the '<em><b>Processinit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processinit</em>' containment reference.
   * @see #setProcessinit(ProcessInit)
   * @see scheduling.dsl.DslPackage#getProcessDSL_Processinit()
   * @model containment="true"
   * @generated
   */
  ProcessInit getProcessinit();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessDSL#getProcessinit <em>Processinit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Processinit</em>' containment reference.
   * @see #getProcessinit()
   * @generated
   */
  void setProcessinit(ProcessInit value);

} // ProcessDSL
