/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.ProcessName#getPName <em>PName</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getProcessName()
 * @model
 * @generated
 */
public interface ProcessName extends Atomic
{
  /**
   * Returns the value of the '<em><b>PName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PName</em>' attribute.
   * @see #setPName(String)
   * @see scheduling.dsl.DslPackage#getProcessName_PName()
   * @model
   * @generated
   */
  String getPName();

  /**
   * Sets the value of the '{@link scheduling.dsl.ProcessName#getPName <em>PName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PName</em>' attribute.
   * @see #getPName()
   * @generated
   */
  void setPName(String value);

} // ProcessName
