/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.RemoveProcess#getProcess <em>Process</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getRemoveProcess()
 * @model
 * @generated
 */
public interface RemoveProcess extends Statement
{
  /**
   * Returns the value of the '<em><b>Process</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' containment reference.
   * @see #setProcess(scheduling.dsl.Process)
   * @see scheduling.dsl.DslPackage#getRemoveProcess_Process()
   * @model containment="true"
   * @generated
   */
  scheduling.dsl.Process getProcess();

  /**
   * Sets the value of the '{@link scheduling.dsl.RemoveProcess#getProcess <em>Process</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' containment reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(scheduling.dsl.Process value);

} // RemoveProcess
