/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scheduler Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.SchedulerDef#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getParameterlist <em>Parameterlist</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getParent <em>Parent</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getGen <em>Gen</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getSvar <em>Svar</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getSchedulerdata <em>Schedulerdata</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getSchedulerinit <em>Schedulerinit</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getHandler <em>Handler</em>}</li>
 *   <li>{@link scheduling.dsl.SchedulerDef#getInterface <em>Interface</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getSchedulerDef()
 * @model
 * @generated
 */
public interface SchedulerDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameterlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameterlist</em>' containment reference.
   * @see #setParameterlist(ParameterList)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Parameterlist()
   * @model containment="true"
   * @generated
   */
  ParameterList getParameterlist();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getParameterlist <em>Parameterlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameterlist</em>' containment reference.
   * @see #getParameterlist()
   * @generated
   */
  void setParameterlist(ParameterList value);

  /**
   * Returns the value of the '<em><b>Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' attribute.
   * @see #setParent(String)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Parent()
   * @model
   * @generated
   */
  String getParent();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getParent <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' attribute.
   * @see #getParent()
   * @generated
   */
  void setParent(String value);

  /**
   * Returns the value of the '<em><b>Gen</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gen</em>' containment reference.
   * @see #setGen(Generate)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Gen()
   * @model containment="true"
   * @generated
   */
  Generate getGen();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getGen <em>Gen</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gen</em>' containment reference.
   * @see #getGen()
   * @generated
   */
  void setGen(Generate value);

  /**
   * Returns the value of the '<em><b>Svar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Svar</em>' containment reference.
   * @see #setSvar(VarDef)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Svar()
   * @model containment="true"
   * @generated
   */
  VarDef getSvar();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getSvar <em>Svar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Svar</em>' containment reference.
   * @see #getSvar()
   * @generated
   */
  void setSvar(VarDef value);

  /**
   * Returns the value of the '<em><b>Schedulerdata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedulerdata</em>' containment reference.
   * @see #setSchedulerdata(SchedulerDataDef)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Schedulerdata()
   * @model containment="true"
   * @generated
   */
  SchedulerDataDef getSchedulerdata();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getSchedulerdata <em>Schedulerdata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedulerdata</em>' containment reference.
   * @see #getSchedulerdata()
   * @generated
   */
  void setSchedulerdata(SchedulerDataDef value);

  /**
   * Returns the value of the '<em><b>Schedulerinit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedulerinit</em>' containment reference.
   * @see #setSchedulerinit(SchedulerInit)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Schedulerinit()
   * @model containment="true"
   * @generated
   */
  SchedulerInit getSchedulerinit();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getSchedulerinit <em>Schedulerinit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedulerinit</em>' containment reference.
   * @see #getSchedulerinit()
   * @generated
   */
  void setSchedulerinit(SchedulerInit value);

  /**
   * Returns the value of the '<em><b>Handler</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Handler</em>' containment reference.
   * @see #setHandler(HandlerDef)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Handler()
   * @model containment="true"
   * @generated
   */
  HandlerDef getHandler();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getHandler <em>Handler</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Handler</em>' containment reference.
   * @see #getHandler()
   * @generated
   */
  void setHandler(HandlerDef value);

  /**
   * Returns the value of the '<em><b>Interface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface</em>' containment reference.
   * @see #setInterface(InterfaceDef)
   * @see scheduling.dsl.DslPackage#getSchedulerDef_Interface()
   * @model containment="true"
   * @generated
   */
  InterfaceDef getInterface();

  /**
   * Sets the value of the '{@link scheduling.dsl.SchedulerDef#getInterface <em>Interface</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interface</em>' containment reference.
   * @see #getInterface()
   * @generated
   */
  void setInterface(InterfaceDef value);

} // SchedulerDef
