/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scheduler Data Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.SchedulerDataDef#getDatadef <em>Datadef</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getSchedulerDataDef()
 * @model
 * @generated
 */
public interface SchedulerDataDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Datadef</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.DataDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datadef</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getSchedulerDataDef_Datadef()
   * @model containment="true"
   * @generated
   */
  EList<DataDef> getDatadef();

} // SchedulerDataDef
