/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.Stm#getIfdef <em>Ifdef</em>}</li>
 *   <li>{@link scheduling.dsl.Stm#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getStm()
 * @model
 * @generated
 */
public interface Stm extends EObject
{
  /**
   * Returns the value of the '<em><b>Ifdef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifdef</em>' containment reference.
   * @see #setIfdef(IfDef)
   * @see scheduling.dsl.DslPackage#getStm_Ifdef()
   * @model containment="true"
   * @generated
   */
  IfDef getIfdef();

  /**
   * Sets the value of the '{@link scheduling.dsl.Stm#getIfdef <em>Ifdef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifdef</em>' containment reference.
   * @see #getIfdef()
   * @generated
   */
  void setIfdef(IfDef value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(Statement)
   * @see scheduling.dsl.DslPackage#getStm_Statement()
   * @model containment="true"
   * @generated
   */
  Statement getStatement();

  /**
   * Sets the value of the '{@link scheduling.dsl.Stm#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(Statement value);

} // Stm
