/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Total Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.TotalStep#getTotalstep <em>Totalstep</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getTotalStep()
 * @model
 * @generated
 */
public interface TotalStep extends Atomic
{
  /**
   * Returns the value of the '<em><b>Totalstep</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Totalstep</em>' attribute.
   * @see #setTotalstep(String)
   * @see scheduling.dsl.DslPackage#getTotalStep_Totalstep()
   * @model
   * @generated
   */
  String getTotalstep();

  /**
   * Sets the value of the '{@link scheduling.dsl.TotalStep#getTotalstep <em>Totalstep</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Totalstep</em>' attribute.
   * @see #getTotalstep()
   * @generated
   */
  void setTotalstep(String value);

} // TotalStep
