/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Block Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.VarBlockDef#getVardef <em>Vardef</em>}</li>
 * </ul>
 *
 * @see scheduling.dsl.DslPackage#getVarBlockDef()
 * @model
 * @generated
 */
public interface VarBlockDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Vardef</b></em>' containment reference list.
   * The list contents are of type {@link scheduling.dsl.VarDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vardef</em>' containment reference list.
   * @see scheduling.dsl.DslPackage#getVarBlockDef_Vardef()
   * @model containment="true"
   * @generated
   */
  EList<VarDefinition> getVardef();

} // VarBlockDef
