/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import scheduling.dsl.DslPackage;
import scheduling.dsl.GenComponent;
import scheduling.dsl.GenConfiguration;
import scheduling.dsl.Generate;
import scheduling.dsl.ProcessGeneration;
import scheduling.dsl.StepGeneration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.impl.GenerateImpl#getGenconfiguration <em>Genconfiguration</em>}</li>
 *   <li>{@link scheduling.dsl.impl.GenerateImpl#getGencomponent <em>Gencomponent</em>}</li>
 *   <li>{@link scheduling.dsl.impl.GenerateImpl#getStepgeneration <em>Stepgeneration</em>}</li>
 *   <li>{@link scheduling.dsl.impl.GenerateImpl#getProcessgeneration <em>Processgeneration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GenerateImpl extends MinimalEObjectImpl.Container implements Generate
{
  /**
   * The cached value of the '{@link #getGenconfiguration() <em>Genconfiguration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGenconfiguration()
   * @generated
   * @ordered
   */
  protected GenConfiguration genconfiguration;

  /**
   * The cached value of the '{@link #getGencomponent() <em>Gencomponent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGencomponent()
   * @generated
   * @ordered
   */
  protected GenComponent gencomponent;

  /**
   * The cached value of the '{@link #getStepgeneration() <em>Stepgeneration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStepgeneration()
   * @generated
   * @ordered
   */
  protected StepGeneration stepgeneration;

  /**
   * The cached value of the '{@link #getProcessgeneration() <em>Processgeneration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessgeneration()
   * @generated
   * @ordered
   */
  protected ProcessGeneration processgeneration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GenerateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getGenerate();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GenConfiguration getGenconfiguration()
  {
    return genconfiguration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGenconfiguration(GenConfiguration newGenconfiguration, NotificationChain msgs)
  {
    GenConfiguration oldGenconfiguration = genconfiguration;
    genconfiguration = newGenconfiguration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__GENCONFIGURATION, oldGenconfiguration, newGenconfiguration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGenconfiguration(GenConfiguration newGenconfiguration)
  {
    if (newGenconfiguration != genconfiguration)
    {
      NotificationChain msgs = null;
      if (genconfiguration != null)
        msgs = ((InternalEObject)genconfiguration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__GENCONFIGURATION, null, msgs);
      if (newGenconfiguration != null)
        msgs = ((InternalEObject)newGenconfiguration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__GENCONFIGURATION, null, msgs);
      msgs = basicSetGenconfiguration(newGenconfiguration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__GENCONFIGURATION, newGenconfiguration, newGenconfiguration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GenComponent getGencomponent()
  {
    return gencomponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGencomponent(GenComponent newGencomponent, NotificationChain msgs)
  {
    GenComponent oldGencomponent = gencomponent;
    gencomponent = newGencomponent;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__GENCOMPONENT, oldGencomponent, newGencomponent);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGencomponent(GenComponent newGencomponent)
  {
    if (newGencomponent != gencomponent)
    {
      NotificationChain msgs = null;
      if (gencomponent != null)
        msgs = ((InternalEObject)gencomponent).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__GENCOMPONENT, null, msgs);
      if (newGencomponent != null)
        msgs = ((InternalEObject)newGencomponent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__GENCOMPONENT, null, msgs);
      msgs = basicSetGencomponent(newGencomponent, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__GENCOMPONENT, newGencomponent, newGencomponent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StepGeneration getStepgeneration()
  {
    return stepgeneration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStepgeneration(StepGeneration newStepgeneration, NotificationChain msgs)
  {
    StepGeneration oldStepgeneration = stepgeneration;
    stepgeneration = newStepgeneration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__STEPGENERATION, oldStepgeneration, newStepgeneration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStepgeneration(StepGeneration newStepgeneration)
  {
    if (newStepgeneration != stepgeneration)
    {
      NotificationChain msgs = null;
      if (stepgeneration != null)
        msgs = ((InternalEObject)stepgeneration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__STEPGENERATION, null, msgs);
      if (newStepgeneration != null)
        msgs = ((InternalEObject)newStepgeneration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__STEPGENERATION, null, msgs);
      msgs = basicSetStepgeneration(newStepgeneration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__STEPGENERATION, newStepgeneration, newStepgeneration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessGeneration getProcessgeneration()
  {
    return processgeneration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProcessgeneration(ProcessGeneration newProcessgeneration, NotificationChain msgs)
  {
    ProcessGeneration oldProcessgeneration = processgeneration;
    processgeneration = newProcessgeneration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__PROCESSGENERATION, oldProcessgeneration, newProcessgeneration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProcessgeneration(ProcessGeneration newProcessgeneration)
  {
    if (newProcessgeneration != processgeneration)
    {
      NotificationChain msgs = null;
      if (processgeneration != null)
        msgs = ((InternalEObject)processgeneration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__PROCESSGENERATION, null, msgs);
      if (newProcessgeneration != null)
        msgs = ((InternalEObject)newProcessgeneration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.GENERATE__PROCESSGENERATION, null, msgs);
      msgs = basicSetProcessgeneration(newProcessgeneration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERATE__PROCESSGENERATION, newProcessgeneration, newProcessgeneration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.GENERATE__GENCONFIGURATION:
        return basicSetGenconfiguration(null, msgs);
      case DslPackage.GENERATE__GENCOMPONENT:
        return basicSetGencomponent(null, msgs);
      case DslPackage.GENERATE__STEPGENERATION:
        return basicSetStepgeneration(null, msgs);
      case DslPackage.GENERATE__PROCESSGENERATION:
        return basicSetProcessgeneration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.GENERATE__GENCONFIGURATION:
        return getGenconfiguration();
      case DslPackage.GENERATE__GENCOMPONENT:
        return getGencomponent();
      case DslPackage.GENERATE__STEPGENERATION:
        return getStepgeneration();
      case DslPackage.GENERATE__PROCESSGENERATION:
        return getProcessgeneration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.GENERATE__GENCONFIGURATION:
        setGenconfiguration((GenConfiguration)newValue);
        return;
      case DslPackage.GENERATE__GENCOMPONENT:
        setGencomponent((GenComponent)newValue);
        return;
      case DslPackage.GENERATE__STEPGENERATION:
        setStepgeneration((StepGeneration)newValue);
        return;
      case DslPackage.GENERATE__PROCESSGENERATION:
        setProcessgeneration((ProcessGeneration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.GENERATE__GENCONFIGURATION:
        setGenconfiguration((GenConfiguration)null);
        return;
      case DslPackage.GENERATE__GENCOMPONENT:
        setGencomponent((GenComponent)null);
        return;
      case DslPackage.GENERATE__STEPGENERATION:
        setStepgeneration((StepGeneration)null);
        return;
      case DslPackage.GENERATE__PROCESSGENERATION:
        setProcessgeneration((ProcessGeneration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.GENERATE__GENCONFIGURATION:
        return genconfiguration != null;
      case DslPackage.GENERATE__GENCOMPONENT:
        return gencomponent != null;
      case DslPackage.GENERATE__STEPGENERATION:
        return stepgeneration != null;
      case DslPackage.GENERATE__PROCESSGENERATION:
        return processgeneration != null;
    }
    return super.eIsSet(featureID);
  }

} //GenerateImpl
