/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import scheduling.dsl.ConstDec;
import scheduling.dsl.DslPackage;
import scheduling.dsl.EnumDec;
import scheduling.dsl.OneDec;
import scheduling.dsl.VarDec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>One Dec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.impl.OneDecImpl#getConst <em>Const</em>}</li>
 *   <li>{@link scheduling.dsl.impl.OneDecImpl#getVar <em>Var</em>}</li>
 *   <li>{@link scheduling.dsl.impl.OneDecImpl#getEnumdec <em>Enumdec</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OneDecImpl extends MinimalEObjectImpl.Container implements OneDec
{
  /**
   * The cached value of the '{@link #getConst() <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConst()
   * @generated
   * @ordered
   */
  protected ConstDec const_;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected VarDec var;

  /**
   * The cached value of the '{@link #getEnumdec() <em>Enumdec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumdec()
   * @generated
   * @ordered
   */
  protected EnumDec enumdec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OneDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getOneDec();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstDec getConst()
  {
    return const_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConst(ConstDec newConst, NotificationChain msgs)
  {
    ConstDec oldConst = const_;
    const_ = newConst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__CONST, oldConst, newConst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConst(ConstDec newConst)
  {
    if (newConst != const_)
    {
      NotificationChain msgs = null;
      if (const_ != null)
        msgs = ((InternalEObject)const_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__CONST, null, msgs);
      if (newConst != null)
        msgs = ((InternalEObject)newConst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__CONST, null, msgs);
      msgs = basicSetConst(newConst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__CONST, newConst, newConst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarDec getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVar(VarDec newVar, NotificationChain msgs)
  {
    VarDec oldVar = var;
    var = newVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__VAR, oldVar, newVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(VarDec newVar)
  {
    if (newVar != var)
    {
      NotificationChain msgs = null;
      if (var != null)
        msgs = ((InternalEObject)var).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__VAR, null, msgs);
      if (newVar != null)
        msgs = ((InternalEObject)newVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__VAR, null, msgs);
      msgs = basicSetVar(newVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__VAR, newVar, newVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnumDec getEnumdec()
  {
    return enumdec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumdec(EnumDec newEnumdec, NotificationChain msgs)
  {
    EnumDec oldEnumdec = enumdec;
    enumdec = newEnumdec;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__ENUMDEC, oldEnumdec, newEnumdec);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumdec(EnumDec newEnumdec)
  {
    if (newEnumdec != enumdec)
    {
      NotificationChain msgs = null;
      if (enumdec != null)
        msgs = ((InternalEObject)enumdec).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__ENUMDEC, null, msgs);
      if (newEnumdec != null)
        msgs = ((InternalEObject)newEnumdec).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.ONE_DEC__ENUMDEC, null, msgs);
      msgs = basicSetEnumdec(newEnumdec, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ONE_DEC__ENUMDEC, newEnumdec, newEnumdec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.ONE_DEC__CONST:
        return basicSetConst(null, msgs);
      case DslPackage.ONE_DEC__VAR:
        return basicSetVar(null, msgs);
      case DslPackage.ONE_DEC__ENUMDEC:
        return basicSetEnumdec(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.ONE_DEC__CONST:
        return getConst();
      case DslPackage.ONE_DEC__VAR:
        return getVar();
      case DslPackage.ONE_DEC__ENUMDEC:
        return getEnumdec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.ONE_DEC__CONST:
        setConst((ConstDec)newValue);
        return;
      case DslPackage.ONE_DEC__VAR:
        setVar((VarDec)newValue);
        return;
      case DslPackage.ONE_DEC__ENUMDEC:
        setEnumdec((EnumDec)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ONE_DEC__CONST:
        setConst((ConstDec)null);
        return;
      case DslPackage.ONE_DEC__VAR:
        setVar((VarDec)null);
        return;
      case DslPackage.ONE_DEC__ENUMDEC:
        setEnumdec((EnumDec)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ONE_DEC__CONST:
        return const_ != null;
      case DslPackage.ONE_DEC__VAR:
        return var != null;
      case DslPackage.ONE_DEC__ENUMDEC:
        return enumdec != null;
    }
    return super.eIsSet(featureID);
  }

} //OneDecImpl
