/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import scheduling.dsl.DslPackage;
import scheduling.dsl.EventStm;
import scheduling.dsl.Opt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Opt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.impl.OptImpl#getEventstm <em>Eventstm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OptImpl extends MinimalEObjectImpl.Container implements Opt
{
  /**
   * The cached value of the '{@link #getEventstm() <em>Eventstm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventstm()
   * @generated
   * @ordered
   */
  protected EventStm eventstm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getOpt();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EventStm getEventstm()
  {
    return eventstm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEventstm(EventStm newEventstm, NotificationChain msgs)
  {
    EventStm oldEventstm = eventstm;
    eventstm = newEventstm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.OPT__EVENTSTM, oldEventstm, newEventstm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEventstm(EventStm newEventstm)
  {
    if (newEventstm != eventstm)
    {
      NotificationChain msgs = null;
      if (eventstm != null)
        msgs = ((InternalEObject)eventstm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.OPT__EVENTSTM, null, msgs);
      if (newEventstm != null)
        msgs = ((InternalEObject)newEventstm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.OPT__EVENTSTM, null, msgs);
      msgs = basicSetEventstm(newEventstm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.OPT__EVENTSTM, newEventstm, newEventstm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.OPT__EVENTSTM:
        return basicSetEventstm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.OPT__EVENTSTM:
        return getEventstm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.OPT__EVENTSTM:
        setEventstm((EventStm)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.OPT__EVENTSTM:
        setEventstm((EventStm)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.OPT__EVENTSTM:
        return eventstm != null;
    }
    return super.eIsSet(featureID);
  }

} //OptImpl
