/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import java.lang.String;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import scheduling.dsl.Attribute;
import scheduling.dsl.DefBehaviorProc;
import scheduling.dsl.DslPackage;
import scheduling.dsl.ProcessConfig;
import scheduling.dsl.ProcessConfiguration;
import scheduling.dsl.ProcessInit;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process Configuration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getName <em>Name</em>}</li>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getParent <em>Parent</em>}</li>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getDefbehaviorproc <em>Defbehaviorproc</em>}</li>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getProcessconfig <em>Processconfig</em>}</li>
 *   <li>{@link scheduling.dsl.impl.ProcessConfigurationImpl#getProcessinit <em>Processinit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessConfigurationImpl extends MinimalEObjectImpl.Container implements ProcessConfiguration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getParent() <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParent()
   * @generated
   * @ordered
   */
  protected static final String PARENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParent() <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParent()
   * @generated
   * @ordered
   */
  protected String parent = PARENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getDefbehaviorproc() <em>Defbehaviorproc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefbehaviorproc()
   * @generated
   * @ordered
   */
  protected DefBehaviorProc defbehaviorproc;

  /**
   * The cached value of the '{@link #getProcessconfig() <em>Processconfig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessconfig()
   * @generated
   * @ordered
   */
  protected ProcessConfig processconfig;

  /**
   * The cached value of the '{@link #getProcessinit() <em>Processinit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessinit()
   * @generated
   * @ordered
   */
  protected ProcessInit processinit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessConfigurationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getProcessConfiguration();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getParent()
  {
    return parent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParent(String newParent)
  {
    String oldParent = parent;
    parent = newParent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__PARENT, oldParent, parent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttribute(Attribute newAttribute, NotificationChain msgs)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE, oldAttribute, newAttribute);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribute(Attribute newAttribute)
  {
    if (newAttribute != attribute)
    {
      NotificationChain msgs = null;
      if (attribute != null)
        msgs = ((InternalEObject)attribute).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE, null, msgs);
      if (newAttribute != null)
        msgs = ((InternalEObject)newAttribute).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE, null, msgs);
      msgs = basicSetAttribute(newAttribute, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE, newAttribute, newAttribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DefBehaviorProc getDefbehaviorproc()
  {
    return defbehaviorproc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefbehaviorproc(DefBehaviorProc newDefbehaviorproc, NotificationChain msgs)
  {
    DefBehaviorProc oldDefbehaviorproc = defbehaviorproc;
    defbehaviorproc = newDefbehaviorproc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC, oldDefbehaviorproc, newDefbehaviorproc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefbehaviorproc(DefBehaviorProc newDefbehaviorproc)
  {
    if (newDefbehaviorproc != defbehaviorproc)
    {
      NotificationChain msgs = null;
      if (defbehaviorproc != null)
        msgs = ((InternalEObject)defbehaviorproc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC, null, msgs);
      if (newDefbehaviorproc != null)
        msgs = ((InternalEObject)newDefbehaviorproc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC, null, msgs);
      msgs = basicSetDefbehaviorproc(newDefbehaviorproc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC, newDefbehaviorproc, newDefbehaviorproc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessConfig getProcessconfig()
  {
    return processconfig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProcessconfig(ProcessConfig newProcessconfig, NotificationChain msgs)
  {
    ProcessConfig oldProcessconfig = processconfig;
    processconfig = newProcessconfig;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG, oldProcessconfig, newProcessconfig);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProcessconfig(ProcessConfig newProcessconfig)
  {
    if (newProcessconfig != processconfig)
    {
      NotificationChain msgs = null;
      if (processconfig != null)
        msgs = ((InternalEObject)processconfig).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG, null, msgs);
      if (newProcessconfig != null)
        msgs = ((InternalEObject)newProcessconfig).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG, null, msgs);
      msgs = basicSetProcessconfig(newProcessconfig, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG, newProcessconfig, newProcessconfig));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessInit getProcessinit()
  {
    return processinit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProcessinit(ProcessInit newProcessinit, NotificationChain msgs)
  {
    ProcessInit oldProcessinit = processinit;
    processinit = newProcessinit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__PROCESSINIT, oldProcessinit, newProcessinit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProcessinit(ProcessInit newProcessinit)
  {
    if (newProcessinit != processinit)
    {
      NotificationChain msgs = null;
      if (processinit != null)
        msgs = ((InternalEObject)processinit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__PROCESSINIT, null, msgs);
      if (newProcessinit != null)
        msgs = ((InternalEObject)newProcessinit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.PROCESS_CONFIGURATION__PROCESSINIT, null, msgs);
      msgs = basicSetProcessinit(newProcessinit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.PROCESS_CONFIGURATION__PROCESSINIT, newProcessinit, newProcessinit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE:
        return basicSetAttribute(null, msgs);
      case DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC:
        return basicSetDefbehaviorproc(null, msgs);
      case DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG:
        return basicSetProcessconfig(null, msgs);
      case DslPackage.PROCESS_CONFIGURATION__PROCESSINIT:
        return basicSetProcessinit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.PROCESS_CONFIGURATION__NAME:
        return getName();
      case DslPackage.PROCESS_CONFIGURATION__PARENT:
        return getParent();
      case DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE:
        return getAttribute();
      case DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC:
        return getDefbehaviorproc();
      case DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG:
        return getProcessconfig();
      case DslPackage.PROCESS_CONFIGURATION__PROCESSINIT:
        return getProcessinit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.PROCESS_CONFIGURATION__NAME:
        setName((String)newValue);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PARENT:
        setParent((String)newValue);
        return;
      case DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC:
        setDefbehaviorproc((DefBehaviorProc)newValue);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG:
        setProcessconfig((ProcessConfig)newValue);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSINIT:
        setProcessinit((ProcessInit)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.PROCESS_CONFIGURATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PARENT:
        setParent(PARENT_EDEFAULT);
        return;
      case DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC:
        setDefbehaviorproc((DefBehaviorProc)null);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG:
        setProcessconfig((ProcessConfig)null);
        return;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSINIT:
        setProcessinit((ProcessInit)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.PROCESS_CONFIGURATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.PROCESS_CONFIGURATION__PARENT:
        return PARENT_EDEFAULT == null ? parent != null : !PARENT_EDEFAULT.equals(parent);
      case DslPackage.PROCESS_CONFIGURATION__ATTRIBUTE:
        return attribute != null;
      case DslPackage.PROCESS_CONFIGURATION__DEFBEHAVIORPROC:
        return defbehaviorproc != null;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSCONFIG:
        return processconfig != null;
      case DslPackage.PROCESS_CONFIGURATION__PROCESSINIT:
        return processinit != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", parent: ");
    result.append(parent);
    result.append(')');
    return result.toString();
  }

} //ProcessConfigurationImpl
