/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import scheduling.dsl.DslPackage;
import scheduling.dsl.SKIP;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SKIP</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SKIPImpl extends ActionImpl implements SKIP
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SKIPImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getSKIP();
  }

} //SKIPImpl
