/**
 * generated by Xtext 2.10.0
 */
package scheduling.dsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import scheduling.dsl.DslPackage;
import scheduling.dsl.IfDef;
import scheduling.dsl.VarBlockDef;
import scheduling.dsl.VarDecl;
import scheduling.dsl.VarSingleDef;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link scheduling.dsl.impl.VarDeclImpl#getIfdef <em>Ifdef</em>}</li>
 *   <li>{@link scheduling.dsl.impl.VarDeclImpl#getVarblockdef <em>Varblockdef</em>}</li>
 *   <li>{@link scheduling.dsl.impl.VarDeclImpl#getVarsingledef <em>Varsingledef</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VarDeclImpl extends MinimalEObjectImpl.Container implements VarDecl
{
  /**
   * The cached value of the '{@link #getIfdef() <em>Ifdef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIfdef()
   * @generated
   * @ordered
   */
  protected IfDef ifdef;

  /**
   * The cached value of the '{@link #getVarblockdef() <em>Varblockdef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarblockdef()
   * @generated
   * @ordered
   */
  protected VarBlockDef varblockdef;

  /**
   * The cached value of the '{@link #getVarsingledef() <em>Varsingledef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarsingledef()
   * @generated
   * @ordered
   */
  protected VarSingleDef varsingledef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.eINSTANCE.getVarDecl();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IfDef getIfdef()
  {
    return ifdef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIfdef(IfDef newIfdef, NotificationChain msgs)
  {
    IfDef oldIfdef = ifdef;
    ifdef = newIfdef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__IFDEF, oldIfdef, newIfdef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIfdef(IfDef newIfdef)
  {
    if (newIfdef != ifdef)
    {
      NotificationChain msgs = null;
      if (ifdef != null)
        msgs = ((InternalEObject)ifdef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__IFDEF, null, msgs);
      if (newIfdef != null)
        msgs = ((InternalEObject)newIfdef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__IFDEF, null, msgs);
      msgs = basicSetIfdef(newIfdef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__IFDEF, newIfdef, newIfdef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarBlockDef getVarblockdef()
  {
    return varblockdef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarblockdef(VarBlockDef newVarblockdef, NotificationChain msgs)
  {
    VarBlockDef oldVarblockdef = varblockdef;
    varblockdef = newVarblockdef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__VARBLOCKDEF, oldVarblockdef, newVarblockdef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarblockdef(VarBlockDef newVarblockdef)
  {
    if (newVarblockdef != varblockdef)
    {
      NotificationChain msgs = null;
      if (varblockdef != null)
        msgs = ((InternalEObject)varblockdef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__VARBLOCKDEF, null, msgs);
      if (newVarblockdef != null)
        msgs = ((InternalEObject)newVarblockdef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__VARBLOCKDEF, null, msgs);
      msgs = basicSetVarblockdef(newVarblockdef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__VARBLOCKDEF, newVarblockdef, newVarblockdef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarSingleDef getVarsingledef()
  {
    return varsingledef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarsingledef(VarSingleDef newVarsingledef, NotificationChain msgs)
  {
    VarSingleDef oldVarsingledef = varsingledef;
    varsingledef = newVarsingledef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__VARSINGLEDEF, oldVarsingledef, newVarsingledef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarsingledef(VarSingleDef newVarsingledef)
  {
    if (newVarsingledef != varsingledef)
    {
      NotificationChain msgs = null;
      if (varsingledef != null)
        msgs = ((InternalEObject)varsingledef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__VARSINGLEDEF, null, msgs);
      if (newVarsingledef != null)
        msgs = ((InternalEObject)newVarsingledef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.VAR_DECL__VARSINGLEDEF, null, msgs);
      msgs = basicSetVarsingledef(newVarsingledef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.VAR_DECL__VARSINGLEDEF, newVarsingledef, newVarsingledef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.VAR_DECL__IFDEF:
        return basicSetIfdef(null, msgs);
      case DslPackage.VAR_DECL__VARBLOCKDEF:
        return basicSetVarblockdef(null, msgs);
      case DslPackage.VAR_DECL__VARSINGLEDEF:
        return basicSetVarsingledef(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.VAR_DECL__IFDEF:
        return getIfdef();
      case DslPackage.VAR_DECL__VARBLOCKDEF:
        return getVarblockdef();
      case DslPackage.VAR_DECL__VARSINGLEDEF:
        return getVarsingledef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.VAR_DECL__IFDEF:
        setIfdef((IfDef)newValue);
        return;
      case DslPackage.VAR_DECL__VARBLOCKDEF:
        setVarblockdef((VarBlockDef)newValue);
        return;
      case DslPackage.VAR_DECL__VARSINGLEDEF:
        setVarsingledef((VarSingleDef)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.VAR_DECL__IFDEF:
        setIfdef((IfDef)null);
        return;
      case DslPackage.VAR_DECL__VARBLOCKDEF:
        setVarblockdef((VarBlockDef)null);
        return;
      case DslPackage.VAR_DECL__VARSINGLEDEF:
        setVarsingledef((VarSingleDef)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.VAR_DECL__IFDEF:
        return ifdef != null;
      case DslPackage.VAR_DECL__VARBLOCKDEF:
        return varblockdef != null;
      case DslPackage.VAR_DECL__VARSINGLEDEF:
        return varsingledef != null;
    }
    return super.eIsSet(featureID);
  }

} //VarDeclImpl
